### ISSUE TITLE
When minimum is dragged to same value as maximum it's impossible to return it back

### ISSUE THREAD

**Issue by jhrcek** [stephenreddek/elm-range-slider#5]
Thank you for this library, looks very nice. I'd like to use it in my project. I just discovered one issue with it:

When minimum value is dragged over to the maximum, it's impossible to return it back.
Try the following steps: drag the maximum knob as far right as possible. Then drag the minimum one over it (also to the rightmost value). Now you're stuck -> unable to drag minimum back.

**Comment by stephenreddek** [comment]
Good catch! I had never gotten into this situation in the maximum end. Do you have any suggestions that would work well for a smaller slider as well as a big slider? One idea is to make the clickable target be wider than the perfectly-circular handle so you can still grab it, but that would be pretty unobvious without some other visual indication. I could also enforce the handles not completely overlapping by some number of pixels. I can do more research, but the first few js sliders I found didn't seem to handle this well either. Once we can settle on a strategy, I'll implement it!

Have you had any other issues I could address at the same time?

**Comment by jhrcek** [comment]
The issue happens not only when the max knob is at the rightmost end of the interval, but any time when minimum knob is at the same value as the maximum. I was thinking about this and came up with the following idea: at the moment you're always rendering minimum knob first in the dom, meaning that it's can become hidden behind the maximum knob.

You could instead put there some condition to decide which order to render the knobs in (e.g. if they are close together, than render the one that has "more space to move in" at the top - by putting it as second in the [list of children](https://github.com/stephenreddek/elm-range-slider/blob/master/src/RangeSlider.elm#L298-L299)). This would make it possible for user to always drag the knobs apart in case he accidentally moves them over each other.

**Comment by stephenreddek** [comment]
That's very interesting. So at any point, they could still overlap, but you'd be guaranteed that at every time at least one handle could be moved? That would provide a better experience than getting completely stuck. Perhaps the "minimum" handle would always get rendered above if it's above a 50% or something like that.

I wonder if there should also be some more possible configuration options for making equal values impossible (only makes sense with steps though) or enforcing a 2+px offset.

**Comment by jhrcek** [comment]
Yes, the trick with midpoint seems to work just fine. I implemented it and opened a PR.

Regarding preventing equal values: For my use case it's not needed because in my app it makes sense to have min & max equal. But perhaps in other cases it might make sense.

On the other hand enforcing 2+px offset doesn't sound like a good idea - if any restriction of minimal selected value range is to be implemented, I'd leave it at the level of model.

**Comment by stephenreddek** [comment]
Fixed by https://github.com/stephenreddek/elm-range-slider/pull/7 and released in version 2.0.0
