### ISSUE TITLE
Change signature of update

### ISSUE THREAD

**Issue by jhrcek** [stephenreddek/elm-range-slider#6]
This is just minor issue, but opening it anyway :-)
The type of `RangeSlide.update` function has nonstandard order of arguments:
`update : RangeSlider -> Msg -> (RangeSlider, Cmd Msg)`

The generally accepted order of arguments for update functions is
`update : Msg -> RangeSlider -> (RangeSlider, Cmd Msg)`

Also looking at the implementation of update I see that it returns `Cmd.none` in all cases.
It would be more user-friendly if the signature changed to 
`update : Msg -> RangeSlider -> RangeSlider`
making it clear that no commands are created

**Comment by stephenreddek** [comment]
Good point about not needing a `Cmd Msg`! I'll go ahead and make both changes.

**Comment by jhrcek** [comment]
Great, thanks for the quick response!

**Comment by stephenreddek** [comment]
Fixed in 2.0.0
