### ISSUE TITLE
Update to elm 0.19

### ISSUE THREAD

**Issue by jhrcek** [stephenreddek/elm-range-slider#8]
Hello @stephenreddek! Now that the elm 0.19 is out, are you planning to update this package? I'm using it in my app which I'd like to update to 0.19 as well. Let me know if you find time to do this in the coming weeks. If not, I might do a PR to migrate this package later..

**Comment by stephenreddek** [comment]
@jhrcek, yes! Thank you for volunteering to assist with a PR, but I've got the migration ready to go just as soon as elm-css gets bumped (which I hear will be by the end of the week).

**Comment by stephenreddek** [comment]
@jhrcek It's been published as [3.0.0](https://package.elm-lang.org/packages/stephenreddek/elm-range-slider/latest/)! Thank you for your patience. I'm sorry it took so long after the release!

**Comment by jhrcek** [comment]
No problem. Thank you for the upgrade!
